tasks:
  - init: npm install
    command: npm run dev
ports:
  - port: 3000
    onOpen: open-preview
    visibility: private

vscode:
  extensions:
    - bradlc.vscode-tailwindcss@0.5.9:yRBWziGXnf16R7jUzlgn5w==