tasks:
  - init: npm install && npm run build
    command: npm run dev
ports:
  - port: 3000
    onOpen: open-preview
    visibility: private

vscode:
  extensions:
    - esbenp.prettier-vscode@5.9.2:/ZjVG4nabMGxTqOcyglnfQ==
    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==
